# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 00:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        ('admin', '0002_logentry_remove_auto_add'),
        ('Elearning_API_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_author',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='userprofile_ptr',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='userprofile_ptr',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
