# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning_API_App', '0003_remove_userprofile_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='userType',
            field=models.CharField(choices=[('ST', 'Student'), ('T', 'Teacher'), ('A', 'Admin')], default='ST', max_length=2),
        ),
    ]
