# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 01:46
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning_API_App', '0004_userprofile_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_Ratings', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('course_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('subscribedCourses', jsonfield.fields.JSONField()),
            ],
            options={
                'abstract': False,
            },
            bases=('Elearning_API_App.userprofile',),
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('averageRatings', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
            ],
            options={
                'abstract': False,
            },
            bases=('Elearning_API_App.userprofile',),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=255)),
                ('video_link', models.CharField(max_length=255)),
                ('video_description', models.CharField(max_length=255)),
                ('video_created_at', models.DateTimeField(auto_now_add=True)),
                ('video_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Video_Relation', to='Elearning_API_App.Course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elearning_API_App.TeacherProfile'),
        ),
    ]
