# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 19:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning_API_App', '0005_auto_20171113_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_ratings_tobeshown', models.FloatField(db_column='ratings_tobeshown', default=0.0)),
                ('rating_give_by_user', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('sum_of_all_ratings', models.FloatField(blank=True, default=0.0, null=True)),
                ('total_number', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('course', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Course_Ratings_Relation', to='Elearning_API_App.Course')),
            ],
        ),
    ]
