# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning_API_App', '0006_courseratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating_Course_User_Bridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_avegrage_ratings',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='rating_course_user_bridge',
            name='course',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Course_Ratings_Bridge_Relation', to='Elearning_API_App.Course'),
        ),
        migrations.AddField(
            model_name='rating_course_user_bridge',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Student_Ratings_Bridge_Relation', to='Elearning_API_App.StudentProfile'),
        ),
    ]
