# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 17:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning_API_App', '0007_auto_20171115_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating_course_user_bridge',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserProfile_Ratings_Bridge_Relation', to=settings.AUTH_USER_MODEL),
        ),
    ]
