# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning_API_App', '0008_auto_20171117_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_Ratings',
        ),
    ]
