# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-30 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning_API_App', '0009_remove_course_course_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Author_Course_Relation', to='Elearning_API_App.TeacherProfile'),
        ),
    ]
