# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-30 18:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning_API_App', '0014_teacherprofile_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Type1_Relation', to=settings.AUTH_USER_MODEL),
        ),
    ]
