# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-30 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning_API_App', '0015_auto_20171130_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_author',
        ),
    ]
