# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 02:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning_API_App', '0003_userprofile_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='averageRatings',
            field=models.IntegerField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
