# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 04:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning_API_App', '0005_auto_20171101_0250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_Ratings', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('course_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elearning_API_App.TeacherProfile')),
            ],
        ),
    ]
