# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning_API_App', '0006_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=255)),
                ('video_link', models.CharField(max_length=255)),
                ('video_description', models.CharField(max_length=255)),
                ('video_parent_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elearning_API_App.Course')),
            ],
        ),
    ]
