# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning_API_App', '0012_remove_course_course_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Video_Relation', to='Elearning_API_App.Course'),
        ),
    ]
